[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vote_solb = "Cc7wBxKzVBoen93fCcGDHtLWTpUyQaJqGdd7uEYJWy8F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lorenzodelia/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
