[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
wba_vault = "z2Q9wm9JsYtyVdicqtPS2WeDjVaKNBgV83pNHiGmTdA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lorenzodelia/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
